name: TN
version: '1.0-SNAPSHOT'
main: me.tenth8602.tN.TN
api-version: '1.21'
commands:
  test:
    permission: TN.admin
    description: "Testing cmd"
    usage: /test
  ah:
    permission: TN.player
    description: "Auction house"
    usage: /ah <page>